server:
  port: 8001

spring:
  rabbitmq:
    host: 49.232.162.145
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
  application:
    name: springcloud-mq
